# Generated by Django 4.1.4 on 2023-01-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snippet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="created_by",
        ),
        migrations.AddField(
            model_name="snippet",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
